import type { Metadata } from "next";
import { Inter, Roboto_Mono , Saira_Stencil_One , Nunito} from 'next/font/google'
 



import "./globals.css";

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
})
 
const roboto_mono = Roboto_Mono({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto-mono',
})

const saira_stencil_one = Saira_Stencil_One({
subsets: ['latin'],
weight: ['400'],
})

const nunito = Nunito({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-nunito',
})



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${roboto_mono.variable} ${saira_stencil_one.className} ${nunito.variable}`}>
    <body>{children}</body>
  </html>
  );
}
